name: Release CD

on:
  push:
    tags:
      - '*'

jobs:
  release-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v2

      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12

      - name: Set up Hub
        run: |
          sudo snap install hub --classic

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 'hub release create
                -a target/hcrevive-*.jar
                -m "$(git describe --tags --abbrev=0)"
                $(git describe --tags --abbrev=0)'
